### ISSUE TITLE
About CPU inference time

### ISSUE THREAD

**Issue by attitudechunfeng** [tianrengao/SqueezeWave#1]
Really nice and practical work! I have one question about the inference time on cpu, did you test the inference time with c++ code or python code? And are there any optimizations utilized?

**Comment by BohanZhai** [comment]
Hi, thank you for your attention. We test inference time on cpu with python code. Actually I wasn't using any optimizations methods.

**Comment by attitudechunfeng** [comment]
Thanks for your reply. I think that it'll be faster with c++ code and platform related optimizations.
